//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raids2020.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Etc
    {
        public int Id { get; set; }
        [DisplayName("Уточнение")]
        [Required(ErrorMessage = "Не имя уточнения")]
        public string Name { get; set; }
        public int PokazatelId { get; set; }
    }
}
