//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raids2020.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ExceptionDate
    {
        public int Id { get; set; }
        public int RispId { get; set; }
        public int RaidId { get; set; }
        [DisplayName("Исключаемая дата")]
        [Required]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
    }
}
