//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raids2020.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Pisp
    {
        public int Id { get; set; }
        [Required]
        [DisplayName("Исполнитель")]
        public int IspId { get; set; }
        [Required]
        [DisplayName("Показатель")]
        public int RpokazatelId { get; set; }

        [DisplayName("Исполнитель")]
        public Isp  Isp { get; set; }
        [DisplayName("Показатель")]
        public Rpokazatel Pokazatel { get; set; }
    }
}
