//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Linq;

namespace Raids2020.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public class Protocol
    {
        public int Id { get; set; }
        [DisplayName("Имя")]
        public string Name { get; set; }
        public List<FileProtocol> FileProtocols { get; set; }
        public List<ProtocolIsp> ProtocolIsps { get; set; }
        public Raid Raid { get; set; }
    }
}
