//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raids2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtocolIsp
    {
        public int Id { get; set; }
        public int ProtocolId { get; set; }
        public int IspId { get; set; }

        public Isp Isp { get; set; }
    }
}
